// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace PersistenceServices.Forms.Domain.EntityFramework.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initial_create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial_create));
        
        string IMigrationMetadata.Id
        {
            get { return "201504070808011_Initial_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
